# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addTwoNumbers.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addTwoNumbers.proto',
  package='addTwoNumbers',
  syntax='proto3',
  serialized_options=b'\252\002\024addTwoNumbersService',
  serialized_pb=b'\n\x13\x61\x64\x64TwoNumbers.proto\x12\raddTwoNumbers\":\n\x13\x41\x64\x64TwoNumberRequest\x12\x10\n\x08\x66irstNum\x18\x01 \x01(\x05\x12\x11\n\tsecondNum\x18\x02 \x01(\x05\"&\n\x11\x41\x64\x64TwoNumberReply\x12\x11\n\tresultVal\x18\x01 \x01(\x05\x32\x65\n\x13\x41\x64\x64TwoNumberService\x12N\n\x06\x41\x64\x64Two\x12\".addTwoNumbers.AddTwoNumberRequest\x1a .addTwoNumbers.AddTwoNumberReplyB\x17\xaa\x02\x14\x61\x64\x64TwoNumbersServiceb\x06proto3'
)




_ADDTWONUMBERREQUEST = _descriptor.Descriptor(
  name='AddTwoNumberRequest',
  full_name='addTwoNumbers.AddTwoNumberRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstNum', full_name='addTwoNumbers.AddTwoNumberRequest.firstNum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secondNum', full_name='addTwoNumbers.AddTwoNumberRequest.secondNum', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=96,
)


_ADDTWONUMBERREPLY = _descriptor.Descriptor(
  name='AddTwoNumberReply',
  full_name='addTwoNumbers.AddTwoNumberReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultVal', full_name='addTwoNumbers.AddTwoNumberReply.resultVal', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['AddTwoNumberRequest'] = _ADDTWONUMBERREQUEST
DESCRIPTOR.message_types_by_name['AddTwoNumberReply'] = _ADDTWONUMBERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddTwoNumberRequest = _reflection.GeneratedProtocolMessageType('AddTwoNumberRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDTWONUMBERREQUEST,
  '__module__' : 'addTwoNumbers_pb2'
  # @@protoc_insertion_point(class_scope:addTwoNumbers.AddTwoNumberRequest)
  })
_sym_db.RegisterMessage(AddTwoNumberRequest)

AddTwoNumberReply = _reflection.GeneratedProtocolMessageType('AddTwoNumberReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDTWONUMBERREPLY,
  '__module__' : 'addTwoNumbers_pb2'
  # @@protoc_insertion_point(class_scope:addTwoNumbers.AddTwoNumberReply)
  })
_sym_db.RegisterMessage(AddTwoNumberReply)


DESCRIPTOR._options = None

_ADDTWONUMBERSERVICE = _descriptor.ServiceDescriptor(
  name='AddTwoNumberService',
  full_name='addTwoNumbers.AddTwoNumberService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=138,
  serialized_end=239,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddTwo',
    full_name='addTwoNumbers.AddTwoNumberService.AddTwo',
    index=0,
    containing_service=None,
    input_type=_ADDTWONUMBERREQUEST,
    output_type=_ADDTWONUMBERREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADDTWONUMBERSERVICE)

DESCRIPTOR.services_by_name['AddTwoNumberService'] = _ADDTWONUMBERSERVICE

# @@protoc_insertion_point(module_scope)
